### PR TITLE
#28 Replaced assert() calls with if/else/raise <Exception>()

### PR DESCRIPTION
**Pull request by syedmalimustafa**

### CODE REVIEW

**Comment by jposada202020** [comment]
It seems that the CI have failed. Could you run pylint locally to verify. Thanks

**Comment by jposada202020** [comment]
It seems that you would need to run black before committing again. the CI is not passing. let me know if you need help with that . Thanks

**Comment by syedmalimustafa** [comment]
> It seems that you would need to run black before committing again. the CI is not passing. let me know if you need help with that . Thanks

Yeah, can you please guide me?

**Comment by jposada202020** [comment]
Yes, no problem just use black before submitting in your clone directory, as shown in this guide
https://learn.adafruit.com/improve-your-code-with-pylint/black

It is easy to intall with a pip install

Thanks

**Review by jposada202020 — APPROVED** [review]
Thanks for the changes

I testes this using the folllowing code to use and change the cases for the exceptions

```python
import time
import sys
import displayio
from blinka_displayio_pygamedisplay import PyGameDisplay
from adafruit_progressbar.progressbar import ProgressBar
from adafruit_progressbar.horizontalprogressbar import (
    HorizontalProgressBar,
    HorizontalFillDirection,
)

display = PyGameDisplay(width=320, height=240, auto_refresh=False)
splash = displayio.Group(max_size=10)
display.show(splash)

color_bitmap = displayio.Bitmap(display.width, display.height, 1)
color_palette = displayio.Palette(1)
color_palette[0] = 0x2266AA  # Teal-ish-kinda

bg_sprite = displayio.TileGrid(color_bitmap, pixel_shader=color_palette, x=0, y=0)
splash.append(bg_sprite)

progress_bar = ProgressBar(
    width=180,
    height=40,
    x=10,
    y=20,
    progress=1.0,
    bar_color=0x1100FF,
    outline_color=0x777777,
)
splash.append(progress_bar)

horizontal_bar = HorizontalProgressBar(
    (10, 80),
    (180, 40),
    min_value=-40,
    max_value=130,
    value=80,
    border_thickness=6,
    margin_size=5,
    fill_color=0x778822,
    outline_color=0x0000FF,
    bar_color=0x00FF00,
    direction=HorizontalFillDirection.LEFT_TO_RIGHT,
)
splash.append(horizontal_bar)
horizontal_bar.border_color = 0x990099
horizontal_bar.margin_size = 7


test_value_range_1 = [99, 100, 99, 1, 0, 1]
test_value_range_2 = [120, 130, 129, -20, -39, -40, -28]
delay = 2
_incr = 1

# Must check display.running in the main loop!
while display.running:

    print("\nDemonstration of legacy functionality and syntax, increment by 0.01")
    for val in range(0, 101):
        if not display.running:
            sys.exit(0)
        _use_value = round((val * 0.01), 2)
        if (val % 10) == 0:
            print(f"Value has reached {_use_value:2}")
        progress_bar.progress = round(_use_value, 2)
        display.refresh()
        time.sleep(0.05)

    print("\nDemonstration of values between 0 and 100 - Horizontal and vertical")
    for val in test_value_range_1:
        if not display.running:
            sys.exit(0)
        print(f"Setting value to {val}")
        horizontal_bar.value = val
        display.refresh()
        time.sleep(delay)

    print("\nDemonstration of Fahrenheit range -40 and 130 - Horizontal and vertical")
    for val in test_value_range_2:
        if not display.running:
            sys.exit(0)
        print(f"Setting value to {val}")
        display.refresh()
        time.sleep(delay)
```

Results as expected
Tested on

```python
Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Adafruit PyPortal Titano with samd51j20
```

**Pull request merged**
