### PR TITLE
Exposing API components in Readthedocs, adding examples to the Readthedocs API

### PR DESCRIPTION
**Pull request by jposada202020**
Currently only adafruit_progressbar.ProgressBar is exposed in the Readhedocs API.
Adding Examples
Adding learning Guides examples

### CODE REVIEW

**Comment by jposada202020** [comment]
@hugodahl Please review.

I noticed that in the API modules it was included
`:show-inheritance:`
I am guessing that the purpose was to show the inheritance diagram. not sure, please ignore this comment if that is not the case.

**Comment by hugodahl** [comment]
> @hugodahl Please review.
> 
> I noticed that in the API modules it was included.
> `:show-inheritance:`
> I am guessing that the purpose was to show the inheritance diagram. not sure, please ignore this comment if that is not the case.

Very close. This indicates to sphinx that the generated documentation should include the inherited properties and methods from the base class(es).

The intention is to avoid having to switch between several different pages, tabs or even disconnected sections of a page in ReadTheDocs.

**Comment by jposada202020** [comment]
@hugodahl Gotcha. thanks, could you review is the documentation after the PR is showing correctly? :)

**Comment by jposada202020** [comment]
Hey @hugodahl, this probably got lost in your inbox, but if you could review the requested changes when you get a chance, that would be great 😄 😄

**Review by hugodahl — APPROVED** [review]
Looks good to me. Nice having the examples inline in the docs!

**Comment by jposada202020** [comment]
Thanks Hugo, for reviewing :) and everything

**Pull request merged**
