### PR TITLE
rename _width and _height attributes

### PR DESCRIPTION
**Pull request by mtowara**
fix for #17

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Please add a comment before `self._bar_width` so that someone doesn't change it back. Thanks!

**Comment by FoamyGuy** [comment]
Thank you for this fix @mtowara 

I can test this with Blinka_Displayio and on a microcontroller device later on tonight.

**Review by FoamyGuy — APPROVED** [review]
I tested these changes successfully with a RasPi 3B+ with TFT Screen hat. Also confirmed no change to behavior on PyPortal.

**Review by tannewt — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
